#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------
port: 4100

# Which thing is this?
# si: SIH internal workshop/lessons
# sp: SIH partner workshops/lessons
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor traning for instance)
carpentry: "si"

# Overall title for pages.
title: "RNA sequencing data analysis using R and the Artemis HPC"
series_name: "SIH Bioinformatics Training"

# What kind of thing is this ("workshop" or "lesson" or "series")?
# IF THIS IS A LESSON, RENAME .lesson.index.md to index.md
# IT IT IS A WORKSHOP, RENAME .workshop.index.md to index.md
# IF THIS IS A SERIES, RENAME .series.index.md to index.md
# THEN edit index.md!
kind: "lesson"



# SETUP
# What software will students need to preinstall on their machines?
bash: "no"
git: "no"
editor: "yes"
python: "no"
R: "yes"
sqlite: "no"
openrefine: "no"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# Please don't change it: <USERNAME>/<PROJECT> is correct.
repository: <USERNAME>/<PROJECT>

# Email address, no mailto:
email: "sih.training@sydney.edu.au"

# Sites.
sih_site: "https://informatics.sydney.edu.au"
sih_github: "https://github.com/Sydney-Informatics-Hub"
sih_pages: "https://sydney-informatics-hub.github.io"
series_home: "https://sydney-informatics-hub.github.io/training-RNAseq/" #edit if you want to point to series landing page
training_home: "https://informatics.sydney.edu.au/training/" # edit if you want to point somewhere else except for SIH

# Carpentries sites
amy_site: "https://amy.software-carpentry.org/workshops"
carpentries_github: "https://github.com/carpentries"
carpentries_pages: "https://carpentries.github.io"
carpentries_site: "https://carpentries.org/"
dc_site: "http://datacarpentry.org"
example_repo: "https://github.com/carpentries/lesson-example"
example_site: "https://carpentries.github.io/lesson-example"
lc_site: "https://librarycarpentry.org/"
swc_github: "https://github.com/swcarpentry"
swc_pages: "https://swcarpentry.github.io"
swc_site: "https://software-carpentry.org"
template_repo: "https://github.com/carpentries/styles"
training_site: "https://carpentries.github.io/instructor-training"
workshop_repo: "https://github.com/carpentries/workshop-template"
workshop_site: "https://carpentries.github.io/workshop-template"

cc_by_human: "https://creativecommons.org/licenses/by/4.0/"
cc_nc_human: "https://creativecommons.org/licenses/by-nc/4.0/"
cc_nc_legal: "https://creativecommons.org/licenses/by-nc/4.0/legalcode"

# .. Surveys
swc_pre_survey: "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
swc_post_survey: "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="
training_post_survey: "https://www.surveymonkey.com/r/post-instructor-training"
dc_pre_survey: "https://www.surveymonkey.com/r/dcpreworkshopassessment?workshop_id="
dc_post_survey: "https://www.surveymonkey.com/r/dcpostworkshopassessment?workshop_id="
lc_pre_survey: "https://www.surveymonkey.com/r/lcpreworkshopsurvey?workshop_id="
lc_post_survey: "https://www.surveymonkey.com/r/lcpostworkshopsurvey?workshop_id="
instructor_pre_survey: "https://www.surveymonkey.com/r/instructor_training_pre_survey?workshop_id="
instructor_post_survey: "https://www.surveymonkey.com/r/instructor_training_post_survey?workshop_id="


# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin/
  - .Rproj.user/

# Turn on built-in syntax highlighting.
highlighter: rouge

# Plugins
plugins:
  - jemoji
